### ISSUE TITLE
ref genome only ?

### ISSUE THREAD

**Issue by colindaven** [kristinebilgrav/sTELLeR#3]
Hi,

is it possible to use a reference genome only as input ? I guess not after reading the README.

It might be interesting to look at BAMs too, but the primary use case would be detection of TEs in genomes.

Thanks,
Colin

**Comment by kristinebilgrav** [comment]
Hi, 
You need to provide a reference genome and an aligned BAM or CRAM file (sample) where steller will search for non-reference TEs. 

Do you mean to use an unaligned denovo genome assembly only?

It does need to be aligned to something ie in a BAM/CRAM format. 
If you only want to look at repeats in a reference I recommend RepeatMasker. 

If you want to look for TEs in an assembly you could align it to a reference and call TEs on this BAM file. If you perform TE detection on an assembly; put -sr to 1 to be able to detect insertions and split reads. 

Hope it helps,
Kristine

**Comment by colindaven** [comment]
Thanks very much ! Yes, I've been looking more at more modern alternatives to RepeatMasker.
